language: php
php:
  - 7
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
before_script:
  - composer self-update
  - composer install --ignore-platform-reqs
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
