<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015-2016 LibreWorks contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache 2.0 License
 */
namespace Caridea\Acl;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 19:11:45.
 *
 * @covers Caridea\Acl\DenyAcl
 */
class DenyAclTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DenyAcl
     */
    protected $object;
    /**
     * @var Target
     */
    protected $target;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->target = new Target('foo', 'bar');
        $this->object = new DenyAcl($this->target);
    }

    /**
     * @covers Caridea\Acl\DenyAcl::can
     */
    public function testCan()
    {
        $this->assertFalse($this->object->can([], null));
    }

    /**
     * @covers Caridea\Acl\DenyAcl::getParent
     */
    public function testGetParent()
    {
        $this->assertNull($this->object->getParent());
    }

    /**
     * @covers Caridea\Acl\DenyAcl::getTarget
     */
    public function testGetTarget()
    {
        $this->assertSame($this->target, $this->object->getTarget());
    }
}
