<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015 LibreWorks contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache 2.0 License
 */
namespace Caridea\Acl;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-30 at 18:55:17.
 */
class TargetTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Caridea\Acl\Target::__construct
     * @covers Caridea\Acl\Target::getId
     */
    public function testGetTargetId()
    {
        $id = 123;
        $object = new Target('foobar', $id);
        $this->assertEquals($id, $object->getId());
    }

    /**
     * @covers Caridea\Acl\Target::__construct
     * @covers Caridea\Acl\Target::getType
     */
    public function testGetTargetType()
    {
        $type = 'foobar';
        $object = new Target($type, 123);
        $this->assertEquals($type, $object->getType());
    }

    /**
     * @covers Caridea\Acl\Target::__toString
     */
    public function testToString()
    {
        $object = new Target('foo', 'bar');
        $this->assertEquals('foo#bar', $object);
    }
    
    /**
     * @covers Caridea\Acl\Target::__construct
     * @expectedException \InvalidArgumentException
     * @expectedExceptionMessage Target type can't be blank
     */
    public function testEmpty()
    {
        new Target('   ', 123);
    }
}
